### PR TITLE
Attempt at changing Country to Timezone

### PR DESCRIPTION
**Pull request by WhoIsJack**

### CODE REVIEW

**Comment by unode** [comment]
Actually, I just noticed that the pull request receives the "option" value instead of the "option-name".
So in the YAML we end up with "Monrovia" instead of "Africa/Monrovia".

I'll try to modify the perl script to include the continent name in the option as well.
It somewhat defeats the purpose of the optgroups but I'd rather have `Africa/Monrovia` in the yaml.

**Comment by unode** [comment]
@WhoIsJack ^

**Comment by unode** [comment]
Modified in ef4a20d12325f464e7ee935f527a52a41f93de9e.
Feel free to revert if applicable.

**Comment by unode** [comment]
Seems like [deployment of the pages is taking forever](https://github.com/Research-Support-Network/research-support-network.github.io/runs/5721483464?check_suite_focus=true). Letting it sit and see if it finishes. May need another push if it fails.

**Comment by WhoIsJack** [comment]
I think the change you made to the time zones is good.

The deployment seems to fail sporadically, in which case it can be rerun from within the Actions tab. It looks like this is a GitHub problem, as it fails with the same message as we saw previously (see #40) - and occasionally it works, without us changing anything. So this one's not on us...

**Pull request merged**
